version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./src:/root/app
#      - ./__docker/data:/root/data
    environment:
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: SO9KNO6YT9OGE39PQCZW
      MINIO_SECRET_KEY: EzH5iGs3qbJr1MwIMf2AUyfqzewgd2qgrk9+i+vU
      MINIO_BUCKET_NAME: testbucket
    working_dir: /root/app
    depends_on:
      - minio
      - hass

  hass:
    image: homeassistant/home-assistant:0.85.1
    volumes:
      - ./__docker/hass-data:/config
    ports:
      - 8123:8123

  minio:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    command: server /data
    volumes:
      - ./__docker/minio-data:/data
    environment:
      MINIO_ACCESS_KEY: SO9KNO6YT9OGE39PQCZW
      MINIO_SECRET_KEY: EzH5iGs3qbJr1MwIMf2AUyfqzewgd2qgrk9+i+vU
    ports:
      - 9001:9000
